### ISSUE TITLE
Add link to to the url

### ISSUE THREAD

**Issue by VrajPandya** [debugger22/github-audio#10]
Can you please add a link to the repository that is generating the music? It would be much more simpler to go to that repo if we see something interesting.

**Comment by debugger22** [comment]
I've already done that. If you click on a disc, it'll take you to the corresponding repository.

**Comment by VrajPandya** [comment]
Oh I am sorry but that does not work in safari.

**Comment by debugger22** [comment]
Working fine for me. Are you talking about mobile Safari?
<img width="1680" alt="screenshot 2016-10-04 13 07 46" src="https://cloud.githubusercontent.com/assets/2821646/19065846/984c58b8-8a33-11e6-8b9b-156a8824cb9f.png">

**Comment by DeveloperACE** [comment]
i think with mobile safari, hover events require you to click twice somehow...

**Comment by saberworks** [comment]
Using firefox on mac here.  Clicking the actual text of the event doesn't do anything even though it's styled like a link (and changes mouse cursor).  You have to actually click on one of the colored circles.  But you have to click it before it overlaps with another circle or it doesn't work again.

**Comment by VrajPandya** [comment]
OK I got it. I was clicking the text all the time. I am sorry.
