### ISSUE TITLE
Viewport and media query issues on safari webView

### ISSUE THREAD

**Issue by VirenMohindra** [debugger22/github-audio#13]
Site looks off on safari mobile. Probably don't need this information and a quick fix might eliminate this issue. 
- iOS 9.0.3
- iPhone 6s 
See attached image below

**Comment by VirenMohindra** [comment]
![2016-10-04 12 24 46](https://cloud.githubusercontent.com/assets/10460518/19088984/769d9304-8a46-11e6-939c-8fa44f947935.png)

**Comment by VirenMohindra** [comment]
Commit # https://github.com/debugger22/github-audio/commit/203a79f5f0bc86324b6b0a41d8584e41d4b72f5d fixed this thanks

Do you think we can add some text to say this is desktop only?

**Comment by VirenMohindra** [comment]
Could you just load music and not display the `area` @480px @debugger22?

**Comment by debugger22** [comment]
> Could you just load music and not display the area @480px @debugger22?

Why would you prefer that?

**Comment by debugger22** [comment]
@VirenMohindra Closing this for now. Feel free to reopen.

**Comment by VirenMohindra** [comment]
Nothing is being displayed as of now when you view on mobile safari

**Comment by debugger22** [comment]
I tried it this morning on iPhone 6. It worked for me.

Anyway, I'll ask few more people to do a test for me.

**Comment by debugger22** [comment]
Closing this for now.
