### ISSUE TITLE
More sounds for issues

### ISSUE THREAD

**Issue by rugk** [debugger22/github-audio#14]
It seems you do not yet make sounds for closing/opening issues. Also commenting on issues might be a soundful event. :wink: 
The same applies to adding emoticons to comments/issues.

**Comment by rugk** [comment]
Okay, so I just saw that you indeed already use sounds for issues. So what about the emoticons?

**Comment by debugger22** [comment]
GitHub's API has a rate limit. It's difficult to do everything. 😉

**Comment by debugger22** [comment]
Closing this for now. Thanks!

**Comment by rugk** [comment]
Mhh, can't you contact GitHub so that they raise the limit for you? I mean you're using it for a special site. :smiley:

**Comment by debugger22** [comment]
Haha 😆 

@fernandez comments!
