### ISSUE TITLE
Wikipedia sounds better

### ISSUE THREAD

**Issue by rugk** [debugger22/github-audio#15]
Sorry, but [Wikipedia](http://listen.hatnote.com/) sounds much better. I am not sure what the reasons are, but there may be some more events, the sounds are more different and there are some low-pitched sounds...

GitHub currently sounds only as if some glasses would be clinking whereas Wikipedia e.g. also has some guitar sounds.

**Comment by debugger22** [comment]
Yea, https://github.audio is throttled. We need some music expert to tune it. :)

**Comment by debugger22** [comment]
Closing this for now.
