### ISSUE TITLE
SocketIO connection refused

### ISSUE THREAD

**Issue by prashant-andani** [debugger22/github-audio#24]
Once the node serve is running and hit the http://localhost:8000
http://localhost/socket.io/?EIO=3&transport=polling&t=LUVnoRW
Connection Refused - i.e ERR_CONNECTION_REFUSED
I'm i missing anything??

**Comment by debugger22** [comment]
Change https://github.com/debugger22/github-audio/blob/master/app/public/js/main.js#L35 to

```
var socket = io(document.location.hostname + ":8000");
```

Sorry for not documenting it.

**Comment by debugger22** [comment]
Feel free to close the issue if it works for you.

**Comment by prashant-andani** [comment]
Yup ... it works now 👍 .. Thank you :)
