### ISSUE TITLE
Where did you get the music files?

### ISSUE THREAD

**Issue by hkalexling** [debugger22/github-audio#28]
May I ask how did you get all those music files in the [sounds folder](https://github.com/debugger22/github-audio/tree/master/app/public/sounds)? Did you play and record them yourself or are they downloaded from some free sources? 

Thanks!

**Comment by debugger22** [comment]
https://github.com/hatnote/listen-to-wikipedia/tree/master/static/sounds

**Comment by hkalexling** [comment]
Thanks!
