### ISSUE TITLE
can't hear comments? 

### ISSUE THREAD

**Issue by JosephMcArthur** [debugger22/github-audio#38]
Not sure if this is a feature or a bug, but you can't hear comments on the player :'(

**Comment by OrkoHunter** [comment]
Hey @JosephMcArthur,

GitHub Audio can only play for the events which are public by [GitHub API](https://developer.github.com/v3/activity/events/). I don't think it receives Comments event.

**Comment by Daniel-Mietchen** [comment]
There is an Issue API that covers comments: https://developer.github.com/v3/issues/events/ .

**Comment by debugger22** [comment]
The events API alone is too much to create a  soothing sound. :)
