### ISSUE TITLE
Add filter option

### ISSUE THREAD

**Issue by lifeiscontent** [debugger22/github-audio#5]
Being able to filter by a particular repo or organization would be cool. That way companies could host this on a TV in their offices 👍 and use it as a calm way to know there are updates

**Comment by debugger22** [comment]
@lifeiscontent Great idea! I'll start working on it as soon as I get time. 

> Other filter option could be : Language

GitHub doesn't sends language info in the endpoint, to get that we'll have to call another endpoint. I'll see to it.
