### ISSUE TITLE
Is this 100% of traffic event of public github?

### ISSUE THREAD

**Issue by tristanbes** [debugger22/github-audio#7]
Hey, 

I was wondering, is the audio we're listening is 100% of Github public repositorie's event or do you filter out a % of the traffic event? (if that's the case, how much % is actually displayed/sounded on your project ?)

**Comment by debugger22** [comment]
This is capturing only 4 events, `IssueCommentEvent`, `PullRequestEvent`, `IssuesEvent` and `PushEvent`. The server tries to even out the number of events in every payload, as some events are higher in number to others, and sends it to connected clients. Client maintains a queue of 100 events and plays it serially with a minimum delay. I tried enabling multiple consumers of these events but it makes the notes too frequent.

I'm experimenting with multiple consumers at the moment to keep it smooth.

**Comment by tristanbes** [comment]
ok great work indeed :-) very pleasant to listen to !

**Comment by debugger22** [comment]
Thanks for the appreciation!
