### ISSUE TITLE
won't work in safari...

### ISSUE THREAD

**Issue by DeveloperACE** [debugger22/github-audio#8]
tried listening in safari 9.1.3 on a mid-2011 iMac (OS X El Capitan 10.11.6) and it came up with this:
![screen shot 2016-10-03 at 7 19 01 pm](https://cloud.githubusercontent.com/assets/17362949/19060614/8244ab1e-899e-11e6-8fc5-d2c717397a9c.png)

disabled all extensions, still the same result. any ideas?

**Comment by DeveloperACE** [comment]
i might like to add that it works perfectly on chrome 53.0.2785.143 (64-bit) on the same machine

**Comment by jayrav13** [comment]
That's weird - I'm able to replicate this error on Safari Version 9.1 (11601.5.17.1) on a mid-2012 MacBook Pro (OS X El Capitan 10.11.4). The error in console is:

```
main.js:258: SyntaxError: Unexpected token '>'
```

Hope this helps in diagnosing - REALLY cool tool!

**Comment by Cardoso222** [comment]
I think this problem occurs because safari don't support js arrow function notation.
![captura de tela 2016-10-04 as 14 42 16](https://cloud.githubusercontent.com/assets/7026517/19085630/56d7965a-8a41-11e6-844d-4003daa7208b.png)

**Comment by debugger22** [comment]
Applied a temporary patch. Can anyone please test?

I has macOS Sierra and it works fine on it.

**Comment by Cardoso222** [comment]
Well, i try here and still the same.
![captura de tela 2016-10-04 as 16 01 00](https://cloud.githubusercontent.com/assets/7026517/19088434/7d6daf6a-8a4c-11e6-8e15-9606510ccfd6.png)

But when i change the line ```259``` to this:
![captura de tela 2016-10-04 as 16 07 39](https://cloud.githubusercontent.com/assets/7026517/19088500/d3b47eda-8a4c-11e6-9a82-2fc4161da615.png)

Works!

**Comment by debugger22** [comment]
@Cardoso222 Thanks! Can I use it in the code?

**Comment by debugger22** [comment]
@Cardoso222  Made the changes.

**Comment by Cardoso222** [comment]
i'm glad to help! @debugger22
